name: Release - Windows x64

on:
  release:
    types: [released]
  workflow_dispatch: null
permissions:
  contents: write
jobs:
  build:
    timeout-minutes: 30
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up MinGW (for GCC)
        uses: egor-tensin/setup-mingw@v3
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 24
      - name: Enable Corepack for Yarn
        run: corepack enable
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.25'
      - name: Install Wails
        run: go install github.com/wailsapp/wails/v3/cmd/wails3@latest
      - name: Downloand and install dependencies
        run: go mod download
      - name: Build
        run: wails3 build
        env:
          CGO_ENABLED: 1
      - name: Rename executable
        run: mv bin/duckySigner.exe bin/duckySigner-win_x64.exe
      - name: Upload executable to latest release
        uses: softprops/action-gh-release@v2
        with:
          fail_on_unmatched_files: true
          files: bin/*.exe
